# This is the main pipeline workflow used to run the demo.

version: '1.0'
stages:
  - prepare
  - build
  - deploy
steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    stage: prepare
    git: github
  BuildProject:
    title: Build project
    stage: build
    image: pulumi/pulumi
    commands:
      - yarn install
  RunPulumi:
    title: Deploying new stack.
    fail_fast: false
    stage: deploy
    image: pulumi/pulumi
    commands:
      - pulumi login
      - pulumi stack select ${{CF_PIPELINE_NAME}} --create
      # (Optional) Use pulumi stack to get more information in CI/CD logs about the current stack
      - pulumi stack
      - pulumi config set aws:region us-east-1
      - pulumi up --non-interactive --yes
